### PR TITLE
FM:Photos tab faq

### PR DESCRIPTION
**Pull request by faith-mutua**
closes https://github.com/onaio/help/issues/204

### CODE REVIEW

**Comment by faith-mutua** [comment]
@rowo, this is ready for review

**Comment by rowo** [comment]
@faith-mutua Recommendation: you wrote "Images uploaded with data can now be viewed..." The help site should exist outside of time — so we should avoid phrases like "the new" or "can now be" since someone could visit this page 5 years from now.

**Comment by rowo** [comment]
Might be nice to talk about the other controls on the top right if it's not too much trouble. There's full screen, zoom, share.
 
screen shot 2016-11-03 at 1 00 52 am

**Comment by rowo** [comment]
@faith-mutua Also this should be updated when downloading full res images is in: https://github.com/onaio/zebra/pull/4727#issuecomment-258437216 which will be soon I guess

**Comment by rowo** [comment]
Peter says should be up Monday but latest Wednesda

**Pull request merged**
