### PR TITLE
FM:Updated FAQ

### PR DESCRIPTION
**Pull request by faith-mutua**
Closes https://github.com/onaio/help/issues/211

### CODE REVIEW

**Comment by msschroeder** [comment]
@rowo can you change these to .jpeg? Before we post.

@faith-mutua we can post this current helpsite, but we can also update the new site as well.

**Comment by rowo** [comment]
@megan I update the images but did not change the file URLs.

**Comment by faith-mutua** [comment]
@msschroeder yeah, that's fine

**Comment by rowo** [comment]
@msschroeder I mentioned above that I did not change the URLs in the files, so it's still calling the larger PNG files.

**Pull request merged**
