### PR TITLE
BM: Form Builder Guide

### PR DESCRIPTION
**Pull request by bmalina**
@rowo please add an image for the form builder guide as discussed.

### CODE REVIEW

**Comment by rowo** [comment]
@bmalina formbuilder-guide

**Comment by bmalina** [comment]
@rowo this is how the user guides will be listed on the help site 
image
Could we have them 3 in a row instead of 4?

**Comment by rowo** [comment]
@bmalina I am not sure how to do it quickly. It might not be worth doing the work since we'll transition to the new design soon.

**Comment by bmalina** [comment]
closes #209 and #242

**Pull request merged**
