### PR TITLE
SM: Transfer project ownership permissions; closes #107

### LINKED ISSUE #107: Define permissions for transferring and create help site article
From @cagulas:

1) Transfer project out of individual account

User must be project admin.

2) Transfer project out of org account

User must be project admin.

3) Transfer project into individual account

No permissions required

4) Transfer project into org account

User must be org admin or org project manager

### PR DESCRIPTION
**Pull request by smusula**

### CODE REVIEW

**Comment by cagulas** [comment]
Some comments below:

1) In other help site articles, we use 'personal' instead of 'individual' account.  I'm fine with either, but think we should try to be consistent.  Do you know what term is used more?
2) For "Transfer a project into an organization account" don't you have to be an org admin or project manager?

Made some other small edits in the branch.

**Comment by smusula** [comment]
* Personal account is used more often
* @cagulas from the tests I did, you don't need to be an org admin, anyone can transfer project ownership to an org account, you’ll not be able to access the transferred project unless you’re a member of the org. @rr confirmed this unless this is bug but that's how it currently works.

**Comment by cagulas** [comment]
@rowo can you confirm if the above is a bug?  @smusula tested and found that no permissions are needed to transfer a project to an org account.  My understanding was always that you had to be an org admin or project manager.

**Comment by rowo** [comment]
@cagulas @smusula @royrutto Letting anyone transfer a project to an org is a bug. Transferring a project is the same as creating a new project, and since organization project creation is restricted (only Project Managers and above in Orgs can create projects), this provides a hack to create publicly available content hosted by the organization or privately to its members.

**Comment by cagulas** [comment]
Ok, I've updated the project transfer permissions in the help site table, so this PR can be merged now.

**Pull request merged**
